### ISSUE TITLE
client发送成功，service端经常不打印日志

### ISSUE THREAD

**Issue by lpcheng1208** [gojuukaze/YTask#11]
client 这边已经拿到任务id了，但是服务端经常性不打印日志

**Comment by lpcheng1208** [comment]
服务端日志：
time="2020-09-28 17:10:50" level=info msg="server[group1|get_next_message]: new msg {Id:4c488400-7ac4-439b-b2cc-84e8bcd4be73 WorkerName:add FuncArgs:[123 44] TaskCtl:{RetryCount:3 RunTime:0001-01-01 00:00:00 +0000 UTC err:<nil>}}"
time="2020-09-28 17:10:50" level=debug msg="server[group1|worker]: save result {Id:4c488400-7ac4-439b-b2cc-84e8bcd4be73 Status:1 FuncReturn:[] RetryCount:0}"
time="2020-09-28 17:10:50" level=debug msg="server[group1|worker]: save result {Id:4c488400-7ac4-439b-b2cc-84e8bcd4be73 Status:4 FuncReturn:[167] RetryCount:0}"
time="2020-09-28 17:10:54" level=info msg="server[group1|get_next_message]: new msg {Id:44f51a3a-a63d-4eb2-a849-940f35ff12e6 WorkerName:add FuncArgs:[123 44] TaskCtl:{RetryCount:3 RunTime:0001-01-01 00:00:00 +0000 UTC err:<nil>}}"
time="2020-09-28 17:10:54" level=debug msg="server[group1|worker]: save result {Id:44f51a3a-a63d-4eb2-a849-940f35ff12e6 Status:1 FuncReturn:[] RetryCount:0}"
time="2020-09-28 17:10:54" level=debug msg="server[group1|worker]: save result {Id:44f51a3a-a63d-4eb2-a849-940f35ff12e6 Status:4 FuncReturn:[167] RetryCount:0}"
time="2020-09-28 17:10:58" level=info msg="server[group1|get_next_message]: new msg {Id:7c1551c9-9cd4-4a87-8ffa-c58b53f01fc6 WorkerName:add FuncArgs:[123 44] TaskCtl:{RetryCount:3 RunTime:0001-01-01 00:00:00 +0000 UTC err:<nil>}}"
time="2020-09-28 17:10:58" level=debug msg="server[group1|worker]: save result {Id:7c1551c9-9cd4-4a87-8ffa-c58b53f01fc6 Status:1 FuncReturn:[] RetryCount:0}"
time="2020-09-28 17:10:58" level=info msg="]: test log"
time="2020-09-28 17:10:58" level=debug msg="server[group1|worker]: save result {Id:7c1551c9-9cd4-4a87-8ffa-c58b53f01fc6 Status:4 FuncReturn:[167] RetryCount:0}"
t

客服端日志：
{"@timestamp":"2020-09-28T17:10:50.762+08","level":"info","content":"taskId:4c488400-7ac4-439b-b2cc-84e8bcd4be73 result:{4c488400-7ac4-439b-b2cc-84e8bcd4be73 4 [167] 0}","trace":"70c41adf84d2a0b6","span":"0.1"}
{"@timestamp":"2020-09-28T17:10:53.476+08","level":"info","content":"taskId:2dfae386-01eb-43c3-8163-bb0c01c1545a result:{2dfae386-01eb-43c3-8163-bb0c01c1545a 4 [167] 0}","trace":"fa97e341f3dbf61c","span":"0.1"}
{"@timestamp":"2020-09-28T17:10:54.743+08","level":"info","content":"taskId:44f51a3a-a63d-4eb2-a849-940f35ff12e6 result:{44f51a3a-a63d-4eb2-a849-940f35ff12e6 4 [167] 0}","trace":"62327fc32abcc8d8","span":"0.1"}
{"@timestamp":"2020-09-28T17:10:57.400+08","level":"info","content":"taskId:20b0263c-d97b-40cd-ae4b-91f6a9349575 result:{20b0263c-d97b-40cd-ae4b-91f6a9349575 4 [167] 0}","trace":"1f361f26135bed78","span":"0.1"}
{"@timestamp":"2020-09-28T17:10:58.543+08","level":"info","content":"taskId:7c1551c9-9cd4-4a87-8ffa-c58b53f01fc6 result:{7c1551c9-9cd4-4a87-8ffa-c58b53f01fc6 4 [167] 0}","trace":"5a26111859f202e3","span":"0.1"}

**Comment by gojuukaze** [comment]
你现在是部署了多个server端吗？

**Comment by lpcheng1208** [comment]
目前用的是单个

**Comment by gojuukaze** [comment]
没打印的id是已经运行了吗？能获取到状态吗

**Comment by lpcheng1208** [comment]
taskId, _ := l.svcCtx.YtaskClient.Send("group1", "add", 123, 44)
result, _ := l.svcCtx.YtaskClient.GetResult(taskId, 2*time.Second, 300*time.Millisecond)

我用的是这种发送之后等结果，rusult 我看到是有结果等

**Comment by lpcheng1208** [comment]
我给你发邮件了，可以加一下联系吗？
