### ISSUE TITLE
rabbitmq 获取消息BUG

### ISSUE THREAD

**Issue by LoveChiba** [gojuukaze/YTask#12]
1、client, err := amqp.Dial(fmt.Sprintf("amqp://%s:%s@%s:%s/{virtual}", user, password, host, port))
如果连接带有Virtual host，需要添加{virtual}
2、Next 如果获取到数据为空，没有处理，且无限获取数据
err = yjson.YJson.UnmarshalFromString(value, &msg) 报错

**Comment by gojuukaze** [comment]
好的，我看一下

**Comment by gojuukaze** [comment]
@LoveChiba 对rabbitmq 不是很熟，能帮忙review一下代码吗 #13

**Comment by LoveChiba** [comment]
不好意思，以前没注意到消息0.0
