### ISSUE TITLE
建议加入任务执行完成回调方法

### ISSUE THREAD

**Issue by anden007** [gojuukaze/YTask#19]
我们假设一种情形，如果用户需要运行一个耗时较久的任务，我们会用YTask把请求加入队列，让后端Workers去运行，但目前YTask只支持用户通过taskid主动尝试获取结果，但此时由于任务需要等待很久，用户早已离开，这种情况我能想到的是用短信或者微信公众号服务消息提醒用户任务完成，但是目前YTask无法提供任务执行回调，所以此想法很难实现。
可能有人想到用定时器定时检测的方式，但如果任务量较多，这种方式很明显不合适。
所以我建议作者在任务完成时，加入一个回调，将已完成的TaskId主动通知给回调函数，让外部系统有可能进行相关通知功能，万分感谢！

**Comment by gojuukaze** [comment]
我理解的大概就是需要运行一组任务 A, B ,C ; A执行完后执行B大概是这样吧

**Comment by anden007** [comment]
可以这么理解，有了任务执行回调，灵活性就大多了

**Comment by gojuukaze** [comment]
嗯，这个需求会加到下一个版本中，基本等到要到明年了

**Comment by gojuukaze** [comment]
[v2.4.0](https://github.com/gojuukaze/YTask/releases/tag/v2.4.0)  已支持
