### ISSUE TITLE
建议加一个可以中止当前正在处理任务的一个功能。

### ISSUE THREAD

**Issue by hellonts** [gojuukaze/YTask#22]
比如下发了一个任务，任务还没执行完我需要终止可以通过taskid停止，不需要停掉程序。

**Comment by gojuukaze** [comment]
这个不太好实现，因为是通过协程执行的，没啥好方法终止协程。之后我研究下吧

**Comment by dxl3811051** [comment]
> 这个不太好实现，因为是通过协程执行的，没啥好方法终止协程。之后我研究下吧

大佬 问下 这个功能实现了么？尝试过asynq 的cancelprocess 但是没有用。希望ytask能有这个功能 ，还是很实用的！

**Comment by gojuukaze** [comment]
> > 这个不太好实现，因为是通过协程执行的，没啥好方法终止协程。之后我研究下吧
> 
> 大佬 问下 这个功能实现了么？尝试过asynq 的cancelprocess 但是没有用。希望ytask能有这个功能 ，还是很实用的！

 目前来说只能在任务开启之前检测一下是否继续，已经运行中的任务不能停止。
