### ISSUE TITLE
msgChan共享问题请教

### ISSUE THREAD

**Issue by xuyue86** [gojuukaze/YTask#24]
大概看了下，msgChan在delayServer 和 inlineServer间共享。
在某时刻运行的worker会不会大于实际设定的workerNum？比如原inlineServer满载运行中，此时delayServer刚好有大量数据进msg。

**Comment by gojuukaze** [comment]
不会的，msgChan的大小固定。worker是从msgChan拿出数据后才创建的， 你可以看 [WorkerGoroutine](https://github.com/gojuukaze/YTask/blob/master/v2/server/inlineServerGoroutine.go#L39) 函数 。
