### ISSUE TITLE
运行client.go经常会出现YTask: timeout

### ISSUE THREAD

**Issue by cxsofware** [gojuukaze/YTask#27]
运行client.go经常会出现YTask: timeout

**Comment by gojuukaze** [comment]
你是说获取结果的时候？这个地方timeout有两种可能，backend设置、连接或者一直没结果。

你具体是怎么做的

**Comment by gojuukaze** [comment]
已解决，因为某些broker未使用连接池，并且复用了链接，导致多个协程争抢导致
