### ISSUE TITLE
任务时间过长，我该如何判断任务是否已经完成

### ISSUE THREAD

**Issue by sairson** [gojuukaze/YTask#36]
如果我有一个耗费时间较长的任务，我需要获取它的执行状态来帮助用户判断当前任务的状态，并当任务执行完成后返回该任务的完成状态。我该怎么办。

**Comment by gojuukaze** [comment]
不太清楚你前后端怎么交互的。一般这种要么是前端轮询；要么接个推送服务，任务完成后通过推送给前端推消息。

如果是前端轮询，建议用通过mysql或者redis等来记录状态。在编写的任务函数中，任务结束后自己改变这个状态。  
前端获取状态时直接查询这个记录就行

**Comment by JiehuiSun** [comment]
做个状态查询接口，前端心跳就好了
