### ISSUE TITLE
兄弟：目前不支持延迟任务队列么

### ISSUE THREAD

**Issue by lb151** [gojuukaze/YTask#4]
希望增加延迟队列功能

**Comment by gojuukaze** [comment]
竟然没收到这条issues的通知，今天才看到。。。。

延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来

**Comment by lb151** [comment]
ok，辛苦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gojuukaze"<notifications@github.com&gt;; 
发送时间: 2020年2月11日(星期二) 上午10:31
收件人: "gojuukaze/YTask"<YTask@noreply.github.com&gt;; 
抄送: "time flies"<120021382@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gojuukaze/YTask] 兄弟：目前不支持延迟任务队列么 (#4)




竟然没收到这条issues的通知，今天才看到。。。。
 
延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来

**Comment by leffss** [comment]
> 竟然没收到这条issues的通知，今天才看到。。。。
> 
> 延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来

以前用了 python 的 celery，在 go 上面找类似的发现了你的 YTASK，虽然好像没有 machinery、gocelery 那么全面，但是也很不错，一般项目都可以用了，也可以看你的源码学习学习，感谢开源！！！

**Comment by gojuukaze** [comment]
> > 竟然没收到这条issues的通知，今天才看到。。。。
> > 延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来
> 
> 以前用了 python 的 celery，在 go 上面找类似的发现了你的 YTASK，虽然好像没有 machinery、gocelery 那么全面，但是也很不错，一般项目都可以用了，也可以看你的源码学习学习，感谢开源！！！

确实不太全，写这个项目是因为machinery用起来不太爽，就自己撸了一个。个人精力有限所以只能优先开发自己需要的功能，不过会一点一点完善的

**Comment by leffss** [comment]
> > > 竟然没收到这条issues的通知，今天才看到。。。。
> > > 延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来
> > 
> > 
> > 以前用了 python 的 celery，在 go 上面找类似的发现了你的 YTASK，虽然好像没有 machinery、gocelery 那么全面，但是也很不错，一般项目都可以用了，也可以看你的源码学习学习，感谢开源！！！
> 
> 确实不太全，写这个项目是因为machinery用起来不太爽，就自己撸了一个。个人精力有限所以只能优先开发自己需要的功能，不过会一点一点完善的

如果能增加延迟任务、间隔任务、cron任务，那就完美了，那就是 celery + apscheduler 的完美结合

**Comment by leffss** [comment]
> > > 竟然没收到这条issues的通知，今天才看到。。。。
> > > 延迟任务排期会在今年中下旬安排上，目前个人在维护3个开源项目，只能轮流来
> > 
> > 
> > 以前用了 python 的 celery，在 go 上面找类似的发现了你的 YTASK，虽然好像没有 machinery、gocelery 那么全面，但是也很不错，一般项目都可以用了，也可以看你的源码学习学习，感谢开源！！！
> 
> 确实不太全，写这个项目是因为machinery用起来不太爽，就自己撸了一个。个人精力有限所以只能优先开发自己需要的功能，不过会一点一点完善的

提交了一个pr

**Comment by gojuukaze** [comment]
v2.2.0 已支持延时任务
