### ISSUE TITLE
大佬可以给个停止任务的例子么？

### ISSUE THREAD

**Issue by dxl3811051** [gojuukaze/YTask#40]
大佬可以给个停止任务的列子么 ？
client:= ser.GetClient()
client.AbortTask(id, 10)
这两句我看明白了，很简单。但是下面的这个
中止运行中的任务
    func abortWorker(ctl *server.TaskCtl, a int) int {
    // do ...

    if f, _ := ctl.IsAbort(); f {
            ctl.Abort("手动中止")
            // 别忘了return
            return 0
    }

    return a * a
}
这个例子 我没看懂啊。。。。。。   能给个详细点的例子么  如何在任务运行中  停止任务

**Comment by gojuukaze** [comment]
就是对于运行中的任务你要在能终止的地方 手动调用 ``ctl.IsAbort()`` 检测是否终止了任务。  

比如下面这个发送短信的任务，你可以在发送短信前检测一次，但已经发送了短信就没必要了，因为这是无意义的。  
另外有的任务比如数据库事务，要根据实际情况来决定在哪可以检测并终止任务

```go
func SendSmS(photo,msg string){

    if f, _ := ctl.IsAbort(); f {
        ctl.Abort("手动中止")
        // 别忘了return
        return 0
    }

    id,code:=Send(photo, msg)

    SaveSendSmSStatus(id, code)
}
```

``IsAbort()`` 返回两个参数： ``isAbort, err``  ，如果从backend获取数据出错 isAbort会设为false ，此时你要根据需求判断是否再次检测

**Comment by dxl3811051** [comment]
我明白你的意思了  这个代码是直接在代码中判断终止的，和我预想的不一样  我以为可以在程序外面去终止运行中的任务，比如 我点击一个按钮 然后终止指定taskid的任务。。。。。。期待大佬的回复

**Comment by dxl3811051** [comment]
> 就是对于运行中的任务你要在能终止的地方 手动调用 `ctl.IsAbort()` 检测是否终止了任务。
> 
> 比如下面这个发送短信的任务，你可以在发送短信前检测一次，但已经发送了短信就没必要了，因为这是无意义的。 另外有的任务比如数据库事务，要根据实际情况来决定在哪可以检测并终止任务
> 
> ```go
> func SendSmS(userId,msg string){
> 
>     phone:=GetUserPhone(userId)
> 
>     if f, _ := ctl.IsAbort(); f {
>         ctl.Abort("手动中止")
>         return
>     }
> 
>     id,code:=Send(phone, msg)
> 
>     SaveStatus(id, code)
> }
> ```
> 
> `IsAbort()` 返回两个参数： `isAbort, err` ，如果从backend获取数据出错 isAbort会设为false ，此时你要根据需求判断是否再次检测

我明白你的意思了 这个代码是直接在代码中判断终止的，和我预想的不一样 我以为可以在程序外面去终止运行中的任务，比如 我点击一个按钮 然后终止指定taskid的任务。。。。。。期待大佬的回复

**Comment by gojuukaze** [comment]
是的，因为任务是通过go协程运行的，go无法中止协程，而且对于运行到一半的任务直接中止也会有问题

**Comment by dxl3811051** [comment]
因为有很几个很大的计算任务  有时候需要临时让别的任务先执行 所以需要终止掉正在执行中的任务 等待别的小任务完成后在执行。。。。。感谢你的回答  我在看看有没有别的方式去实现
