### ISSUE TITLE
time="xxxx" level=error msg="server[server_name]: goroutine get_next_message get msg error, MOVED 5876 xxx.xxx.xxx.xxx:6379"

### ISSUE THREAD

**Issue by RaphaelL2e** [gojuukaze/YTask#50]
你好，遇到了这个问题。请问是什么原因导致的？

**Comment by RaphaelL2e** [comment]
time="2023-03-17 08:41:12" level=error msg="server[perception-evaluation]: goroutine get_next_message get msg error, MOVED 5876 10.244.8.203:6379"

**Comment by RaphaelL2e** [comment]
https://github.com/gojuukaze/YTask/blob/v3.0.1/v3/server/inlineServerGoroutine.go#L27
看起来是在这里死循环了

**Comment by RaphaelL2e** [comment]
请问什么情况下会发生这种问题呢

**Comment by gojuukaze** [comment]
这是从broker获取消息失败，看起来你应该是用来redis集群，默认的redis broker是不支持集群连接的。你需要自己实现broker。

实现也比较简单，直接复制现在的redis相关代码，直接改下连接那块的代码就行。

https://github.com/gojuukaze/YTask/blob/1524b236b6029a3f5e000c45cb8249d057f26138/drives/redis/redis.go#L14-L22

改了后大概是这样的：

```go
client := Client{
    redisPool :  redis.NewClusterClient(&redis.ClusterOptions{
        Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
    })
}
```

不过我没使用过 `github.com/go-redis/redis` 的集群，改完之后建议你跑下测试（可以直接用redis的测试用例跑https://github.com/gojuukaze/YTask/tree/master/drives/redis/test ）

**Comment by RaphaelL2e** [comment]
好的 我试一下。感谢！

**Comment by RaphaelL2e** [comment]
请问可以兼容同时支持单机版和集群版redis吗？

**Comment by gojuukaze** [comment]
这样的话，你需要增加broker new时的参数，根据参数不同选择连接单机还是集群

**Comment by RaphaelL2e** [comment]
好的

**Comment by RaphaelL2e** [comment]
你好，我们是在集群版的基础上增加了一个这个redis代理，https://github.com/joyieldInc/predixy 
 貌似不能通过更改集群连接方式修复上述问题吧。

**Comment by RaphaelL2e** [comment]
https://github.com/gojuukaze/YTask/pull/51 这部分redis driver是兼容集群版的改动

**Comment by gojuukaze** [comment]
> #51 这部分redis driver是兼容集群版的改动

由于这部分代码对兼容性有影响，我拉了个f-50的分支，你重新提交请求合并到f-50。

我周末的时候会进行测试合并到主分支。

**Comment by RaphaelL2e** [comment]
> 你好，我们是在集群版的基础上增加了一个这个redis代理，https://github.com/joyieldInc/predixy 貌似不能通过更改集群连接方式修复上述问题吧。
那关于redis proxy导致的bug，请问有什么可以提供的帮助吗

**Comment by gojuukaze** [comment]
> > 你好，我们是在集群版的基础上增加了一个这个redis代理，https://github.com/joyieldInc/predixy 貌似不能通过更改集群连接方式修复上述问题吧。
> > 那关于redis proxy导致的bug，请问有什么可以提供的帮助吗

这个你的需要向 predixy 或者 go-redis 的作者询问了，我没用过这个，无法提供更多帮助。

不过看起来无法连接predixy并不是个例，issue里有很多无法连接的问题。

另外，你现在的代码应该是能连接predixy 的吧，能连的话建议用你现在的redis库实现个自己的broker（不过这个broker就别提交到这个项目了，自用就行）
